spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jjan
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true